# ===============================
# FRONTEND BUILD (VITE)
# ===============================
FROM node:20-alpine AS frontend-build

WORKDIR /app/frontend

COPY frontend/package*.json ./
RUN npm install

COPY frontend/ ./
RUN npm run build


# ===============================
# BACKEND BUILD (SPRING 17)
# ===============================
FROM maven:3.9.6-eclipse-temurin-17 AS backend-build

WORKDIR /app/backend

COPY backend/pom.xml ./
RUN mvn dependency:go-offline

COPY backend/ ./
RUN mvn clean package -DskipTests


# ===============================
# RUNTIME FINAL
# ===============================
FROM eclipse-temurin:17-jdk-alpine

WORKDIR /app

COPY --from=backend-build /app/backend/target/*.jar app.jar
COPY --from=frontend-build /app/frontend/dist /app/static

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]