spring:
  application:
    name: mindtrack

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/mindtrack
    username: mindtrack
    password: mindtrack

server:
  port: 8080
