version: "3.9"

services:
  mindtrack-api:
    build: .
    container_name: mindtrack-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mindtrack
      SPRING_DATASOURCE_USERNAME: mindtrack
      SPRING_DATASOURCE_PASSWORD: mindtrack
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  db:
    image: postgres:16
    container_name: mindtrack-db
    restart: always
    environment:
      POSTGRES_DB: mindtrack
      POSTGRES_USER: mindtrack
      POSTGRES_PASSWORD: mindtrack
    ports:
      - "5432:5432"
